# Generated by Django 2.2.5 on 2019-10-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicModulesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduletitle', models.CharField(max_length=200)),
                ('modulefiels', models.TextField(max_length=65500)),
                ('moduledescription', models.TextField(max_length=5000)),
                ('createat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
